services:
  - type: web
    name: aqua-marketplace
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mystore.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: DEBUG
        value: "True"
      - key: SECRET_KEY
        generateValue: true